import type { ResumeData } from "@/types";

export const mockResumeData: ResumeData = {
  profile: {
    id: "profile-1",
    name: "张三",
    email: "zhangsan@example.com",
    phone: "138-0000-0000",
    title: "高级产品经理",
    summary:
      "8年互联网产品经验，专注B端SaaS与C端增长，主导过千万级DAU产品从0到1。擅长用户研究、数据驱动决策和跨团队协作，具备技术背景，能与研发团队高效沟通。",
    location: "上海",
    website: "https://zhangsan.dev",
    linkedin: "https://linkedin.com/in/zhangsan",
  },
  timeline: [
    {
      id: "tl-1",
      company: "字节跳动",
      position: "高级产品经理",
      startDate: "2021-03",
      endDate: "至今",
      description:
        "负责企业级协作工具产品线，管理5人产品团队，推动产品从MVP到规模化增长。",
      highlights: [
        "主导飞书文档协作功能重构，用户活跃度提升40%",
        "建立产品数据指标体系，实现数据驱动决策闭环",
        "推动跨部门OKR对齐机制，产研效率提升30%",
      ],
      projects: [
        {
          id: "proj-1",
          name: "飞书文档3.0",
          description: "企业级在线文档协作平台重构",
          role: "产品负责人",
          highlights: [
            "重新设计协作编辑架构，支持万人同时在线编辑",
            "引入AI辅助写作功能，用户满意度达92%",
          ],
          techStack: ["React", "WebSocket", "CRDT", "Node.js"],
        },
      ],
      skills: ["B端产品", "团队管理", "数据分析", "OKR"],
      order: 0,
      careerKind: "fulltime",
      storyTitle: "从核心模块负责人到产品团队负责人",
      storyScene: "企业协作工具进入规模化增长阶段，需要把单点功能能力沉淀为稳定、可复用的产品系统。",
      storyChallenge: "协作链路长、核心功能使用深度不足，产品团队需要同时解决体验、效率和指标闭环。",
      storyAction: "主导文档协作能力重构，建立数据指标体系，并推动跨部门 OKR 对齐机制。",
      storyOutcome: "用户活跃度提升 40%，产研效率提升 30%，产品线从 MVP 进入规模化增长。",
      storyReflection: "这段经历体现了从独立负责功能，到用机制和团队协作推动复杂产品线增长的升级。",
      evidenceProblem: "企业协作场景复杂，跨团队目标和数据口径不统一。",
      evidenceAction: "重构核心协作功能，建立指标体系，并推动产研 OKR 对齐。",
      evidenceResult: "用户活跃度提升 40%，产研效率提升 30%。",
      evidenceProof: "覆盖企业级协作工具产品线，并管理 5 人产品团队。",
      promotionStages: [
        {
          id: "stage-1",
          title: "产品经理",
          period: "2021.03 - 2022.06",
          teamScale: "独立负责核心模块",
          leadershipType: "none",
          responsibility: "负责文档协作核心功能重构，从用户反馈和数据表现中确定优先级。",
          outcome: "完成核心协作能力升级，用户活跃度明显提升。",
          reflection: "这一阶段重点是把复杂需求拆成可交付、可验证的产品方案。",
        },
        {
          id: "stage-2",
          title: "产品负责人",
          period: "2022.07 - 2023.12",
          teamScale: "虚线协同 3-5 人",
          leadershipType: "dotted",
          responsibility: "推动跨部门 OKR 对齐、需求排期和版本节奏管理。",
          outcome: "产研效率提升 30%，关键项目延期风险下降。",
          reflection: "这一阶段开始从功能交付转向机制建设和跨团队协作。",
        },
        {
          id: "stage-3",
          title: "产品团队负责人",
          period: "2024.01 - 至今",
          teamScale: "实线管理 5 人团队",
          leadershipType: "solid",
          responsibility: "负责产品线方向判断、团队分工和规模化增长目标。",
          outcome: "推动产品从 MVP 到规模化增长，并持续建立数据驱动决策闭环。",
          reflection: "这一阶段的重点是用组织能力和产品判断共同支撑业务结果。",
        },
      ],
    },
    {
      id: "tl-2",
      company: "阿里巴巴",
      position: "产品经理",
      startDate: "2018-07",
      endDate: "2021-02",
      description:
        "负责钉钉智能办公平台核心模块，覆盖百万企业用户，推动平台化转型。",
      highlights: [
        "主导钉钉审批流引擎重构，处理效率提升60%",
        "设计低代码搭建平台，降低企业定制成本70%",
        "获得集团年度最佳产品创新奖",
      ],
      projects: [
        {
          id: "proj-2",
          name: "钉钉审批流3.0",
          description: "企业审批流程引擎重构与智能化升级",
          role: "核心产品经理",
          highlights: [
            "设计可视化流程编辑器，支持复杂条件分支",
            "接入AI智能推荐审批模板",
          ],
          techStack: ["Vue", "Workflow Engine", "Machine Learning"],
        },
      ],
      skills: ["SaaS", "平台产品", "低代码", "流程设计"],
      order: 1,
      careerKind: "fulltime",
    },
    {
      id: "tl-3",
      company: "星河生活",
      position: "产品经理",
      startDate: "2016-06",
      endDate: "2018-06",
      description:
        "负责外卖C端用户增长与留存，通过数据分析驱动产品迭代，实现关键指标增长。",
      highlights: [
        "设计用户分层运营策略，月活提升25%",
        "优化下单转化漏斗，整体转化率提升15%",
        "搭建A/B测试平台，推动团队实验文化",
      ],
      projects: [
        {
          id: "proj-3",
          name: "智能推荐系统",
          description: "外卖首页个性化推荐优化",
          role: "产品经理",
          highlights: [
            "千人千面推荐策略设计",
            "CTR提升18%，客单价提升8%",
          ],
          techStack: ["Python", "TensorFlow", "Spark"],
        },
      ],
      skills: ["C端产品", "增长策略", "数据分析", "A/B测试"],
      order: 2,
      careerKind: "fulltime",
    },
    {
      id: "tl-4",
      company: "网易",
      position: "初级产品经理",
      startDate: "2014-07",
      endDate: "2016-05",
      description:
        "参与网易云音乐社区功能设计，完成从产品助理到独立负责人的成长。",
      highlights: [
        "负责评论区互动功能迭代，日均UGC量增长200%",
        "设计歌单分享传播机制，带来15%新增用户",
      ],
      projects: [],
      skills: ["用户体验", "社区产品", "竞品分析"],
      order: 3,
      careerKind: "fulltime",
    },
  ],
  skills: [
    {
      id: "sk-root",
      name: "产品技能",
      category: "root",
      level: 5,
      parentId: null,
    },
    {
      id: "sk-1",
      name: "B端产品",
      category: "产品设计",
      level: 5,
      parentId: "sk-root",
    },
    {
      id: "sk-2",
      name: "C端产品",
      category: "产品设计",
      level: 4,
      parentId: "sk-root",
    },
    {
      id: "sk-3",
      name: "数据分析",
      category: "数据能力",
      level: 5,
      parentId: "sk-root",
    },
    {
      id: "sk-4",
      name: "SQL",
      category: "数据能力",
      level: 4,
      parentId: "sk-3",
    },
    {
      id: "sk-5",
      name: "Python",
      category: "数据能力",
      level: 3,
      parentId: "sk-3",
    },
    {
      id: "sk-6",
      name: "Axure",
      category: "设计工具",
      level: 5,
      parentId: "sk-root",
    },
    {
      id: "sk-7",
      name: "Figma",
      category: "设计工具",
      level: 4,
      parentId: "sk-root",
    },
    {
      id: "sk-8",
      name: "用户研究",
      category: "用户体验",
      level: 4,
      parentId: "sk-root",
    },
    {
      id: "sk-9",
      name: "项目管理",
      category: "管理能力",
      level: 4,
      parentId: "sk-root",
    },
    {
      id: "sk-10",
      name: "团队管理",
      category: "管理能力",
      level: 4,
      parentId: "sk-9",
    },
    {
      id: "sk-11",
      name: "增长策略",
      category: "产品设计",
      level: 4,
      parentId: "sk-2",
    },
    {
      id: "sk-12",
      name: "A/B测试",
      category: "数据能力",
      level: 4,
      parentId: "sk-3",
    },
  ],
  architecture: [
    {
      id: "arch-1",
      title: "用户增长体系",
      description: "覆盖拉新、激活、留存、变现全链路的增长策略体系",
      type: "business",
      industry: "internet",
      position: { x: 100, y: 100 },
      parentId: null,
      relatedTimelineIds: ["tl-3"],
    },
    {
      id: "arch-2",
      title: "企业协作平台",
      description: "面向企业的文档协作、审批流、项目管理一站式解决方案",
      type: "business",
      industry: "internet",
      position: { x: 400, y: 100 },
      parentId: null,
      relatedTimelineIds: ["tl-1", "tl-2"],
    },
    {
      id: "arch-3",
      title: "数据中台",
      description: "统一的数据采集、分析和可视化平台，支撑业务决策",
      type: "technical",
      industry: "internet",
      position: { x: 250, y: 300 },
      parentId: null,
      relatedTimelineIds: ["tl-1", "tl-2", "tl-3"],
    },
    {
      id: "arch-4",
      title: "低代码平台",
      description: "可视化搭建企业应用，降低定制开发成本",
      type: "technical",
      industry: "internet",
      position: { x: 550, y: 300 },
      parentId: "arch-2",
      relatedTimelineIds: ["tl-2"],
    },
  ],
  education: [
    {
      id: "edu-1",
      school: "浙江大学",
      degree: "硕士",
      major: "计算机科学与技术",
      startDate: "2012-09",
      endDate: "2014-06",
    },
    {
      id: "edu-2",
      school: "浙江大学",
      degree: "学士",
      major: "信息管理与信息系统",
      startDate: "2008-09",
      endDate: "2012-06",
    },
  ],
  roleUnderstanding: {
    targetRoleTitle: "高级产品经理（企业协作方向）",
    companyContext: "目标团队处于从功能交付向平台化能力升级阶段",
    oneLineInterpretation: "该岗位核心是把复杂协作需求沉淀为可规模复用的产品能力。",
    priorityProblems: [
      {
        id: "rp-1",
        problem: "跨团队协作链路长，需求到上线周期不稳定",
        impact: "影响交付效率与业务响应速度",
        evidence: "季度内多条关键需求延期超过2周",
      },
      {
        id: "rp-2",
        problem: "核心功能使用深度不足，活跃停留在浅层行为",
        impact: "影响续费与产品价值感知",
        evidence: "高频用户中高级功能渗透率低于20%",
      },
      {
        id: "rp-3",
        problem: "数据指标口径不统一，决策讨论成本高",
        impact: "影响优先级判断与资源配置",
        evidence: "同一指标在不同报表中存在明显偏差",
      },
    ],
    ninetyDayPlan: {
      day0To30: "完成业务访谈与链路诊断，建立统一目标与指标基线。",
      day31To60: "围绕关键问题输出方案原型，推动跨团队评审与范围收敛。",
      day61To90: "推动核心方案上线并跟踪效果，固化指标复盘机制。",
    },
    experienceMappings: [
      {
        id: "rem-1",
        requirement: "搭建跨团队协同机制，提升项目交付效率",
        myExperience: "在字节主导产研OKR对齐机制与节奏管理",
        outcomeEvidence: "团队协作效率提升30%，需求延期率显著下降",
      },
      {
        id: "rem-2",
        requirement: "通过数据驱动产品迭代，提高关键指标",
        myExperience: "在增长业务中负责漏斗优化与A/B实验体系建设",
        outcomeEvidence: "转化率提升15%，月活提升25%",
      },
    ],
  },
};
