import type { PresentationDraft } from "./types";

export const FIXTURE_PRESENTATION_DRAFT: PresentationDraft = {
  id: "fixture-groot-arch-story",
  schemaVersion: 1,
  sourceResumeRevision: "fixture-v1",
  targetRole: "AI Agent 产品总监",
  template: "agent-product-arc",
  themeId: "light-story",
  createdAt: "2026-04-30T00:00:00.000Z",
  updatedAt: "2026-04-30T00:00:00.000Z",
  slides: [
    {
      id: "hero",
      kind: "hero",
      title: "Groot-Arch 一体化智能工具链",
      subtitle: "国产汽车电子 · AI Agent 驱动",
      body: "以云原生架构设计平台为核心，集成五个受控式 AI Agent 与 RAG 知识库，覆盖从需求分析到运维观测的完整工程生命周期。服务汽车、军工、航天领域十余家客户，支撑百人级研发团队日常运作。",
      bullets: [
        "5 个 AI Agent",
        "产品团队 10 人",
        "服务研发 100+ 人",
        "行业覆盖 汽车·军工·航天",
      ],
      visualizations: [{ type: "orbit", data: { core: "Groot-Arch", satellites: ["AI Agent", "通信设计", "诊断设计", "服务仿真", "DevOps", "服务编排"] } }],
      sourceRefs: [{ type: "profile" }],
    },
    {
      id: "foundation",
      kind: "foundation",
      title: "从一线业务切入，建立产品方法论",
      subtitle: "京东·百度·经纬恒润",
      body: "三段大厂产品实习奠定了产品思维基础。在京东健康完成医生管理后台从 0 到 1 搭建，在百度参与问诊流程优化（问诊单量 +5.1%）。进入经纬恒润后，主动申请去业务部门委培，深入通信工程师的日常工作。",
      bullets: [
        "京东健康：医生管理后台从 0 到 1",
        "百度健康：问诊流程优化，单量 +5.1%",
        "经纬恒润：一线委培，理解汽车研发痛点",
      ],
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "tension",
      kind: "tension",
      title: "中国汽车工业的研发基础设施被国外垄断二十年",
      subtitle: "V 模型六个核心设计环节的国产替代地图",
      body: "V 模型左侧六个核心设计环节：需求管理、功能设计、系统设计、软件设计、通信设计、诊断设计。四个环节完全没有国产产品可用，两个停留在桌面单机形态，六个环节均不具备任何 AI 辅助能力。这不是市场占有率的问题——这是研发基础设施的对外依赖。",
      bullets: [
        "需求管理 / 功能设计 / 系统设计 / 软件设计：无国产替代",
        "通信设计 / 诊断设计：桌面单机形态，无协同",
        "六个环节均无 AI 能力",
        "底层架构协同平台被 PREEvision / SystemWeaver 控制",
      ],
      visualizations: [{ type: "v-model", data: { highlightDomain: "left", showGaps: true } }],
      overlayIds: ["ov-conflict-types"],
      sourceRefs: [{ type: "roleUnderstanding" }],
    },
    {
      id: "platform-build",
      kind: "platform_build",
      title: "把方法论变成平台：六个模块运行在统一数据模型上",
      subtitle: "国科础石 · 产品经理 → 产品总监",
      body: "角色升级为架构设计工具产品负责人。核心任务是将 VDE 和 DDE 背后那套平台基础设施抽象出来，补齐需求、功能、系统、软件四个模块，让六个环节共享同一套数据模型、同一套权限体系、同一套协同机制。",
      bullets: [
        "需求管理：对标 IBM DOORS，全追溯链路",
        "功能设计：对标 Sparx EA，UML/SysML 建模",
        "系统设计：对标 PREEvision，整车级架构",
        "软件设计：组件/接口/运行实体",
        "通信设计：VDE Cloud 能力抽象为平台模块",
        "诊断设计：DDE 能力抽象为平台模块",
      ],
      visualizations: [{ type: "v-model", data: { highlightDomain: "left", showGaps: false, allCovered: true } }],
      overlayIds: ["ov-arch-detail", "ov-platform"],
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "agent-leap",
      kind: "agent_leap",
      title: "平台统一了数据——下一步是用 AI Agent 重新定义工程效率",
      subtitle: "产品总监 · AI Agent · 知识库",
      body: "六个模块在统一数据模型上运行之后，真正的质变机会出现了：平台积累的结构化工程数据，让领域 AI Agent 从概念变为可行。晋升产品总监后，管理的核心命题从「搭建平台」变为「定义 AI 战略」。",
      bullets: [
        "文档生成 Agent：基于模板和历史文档生成工程规范初稿",
        "模型生成 Agent：根据结构化需求自动生成架构建模草稿",
        "一致性校验 Agent：跨文档、跨模块自动检查需求一致性",
        "方案推荐 Agent：基于历史项目数据推荐设计方案",
        "知识检索 Agent：RAG 驱动的跨项目知识搜索",
      ],
      overlayIds: ["ov-agent-workflow", "ov-rag-detail"],
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "fullstack",
      kind: "lifecycle",
      title: "从架构设计出发，覆盖全生命周期",
      subtitle: "Agent 贯穿每个阶段",
      body: "以 Groot-Arch 为设计起点，依次完成服务编排、仿真验证、DevOps 持续交付和运维观测。五个阶段在统一数据模型上流转——AI Agent 与 RAG 知识库作为智能层贯穿全程。",
      bullets: [
        "Groot-Arch 架构设计平台（起点）",
        "服务编排：SOA 服务场景建模",
        "服务仿真：云原生引擎，硬件无依赖",
        "DevOps：需求/缺陷/代码一体化",
        "观测运维：全链路追踪 · OTA · 具身智能延伸",
      ],
      visualizations: [{ type: "pipeline", data: {} }],
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "impact",
      kind: "impact",
      title: "10+ 客户 · 50%+ 效率 · 三年成长弧线",
      subtitle: "从产品实习生到产品总监",
      body: "经纬恒润期间 VDE Cloud 交付一汽红旗、诊断参数系统交付广汽集团；国科础石期间平台及工具链整体落地东风汽车，覆盖汽车/军工/航天三大领域。管理约十人产品团队，代表公司参与工信部汽车工具链摸底调研。",
      bullets: [
        "一汽红旗：VDE Cloud 商业化部署",
        "广汽集团：诊断参数系统规模化部署",
        "东风汽车：一体化工具链整体落地",
        "工信部调研：汽车工具链摸底",
        "团队管理：约十人产品团队",
      ],
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "resolution",
      kind: "resolution",
      title: "从桌面单机零 AI，到云原生 Agent 驱动的架构代际更替",
      subtitle: "四年前 vs 四年后",
      body: "四年前，六个环节中两个勉强有国产替代，且都是桌面单机形态，零 AI 能力。四年后，全部六个环节由国产产品覆盖，全部为 Web 云原生架构，统一数据模型支撑五个受控式 AI Agent 与 RAG 知识库——这些能力在桌面单机架构上永远无法实现。这不是追赶，这是架构代际的更替。",
      bullets: [
        "国产替代：6/6 环节全面覆盖",
        "架构代际：桌面单机 → Web 云原生",
        "AI 能力：零 → 5 Agent + RAG 知识库",
        "商业闭环：红旗 · 广汽 · 东风 · 军工 · 航天",
      ],
      visualizations: [{ type: "v-model", data: { highlightDomain: "both", allCovered: true, showBefore: true } }],
      sourceRefs: [{ type: "profile" }],
    },
  ],
  overlays: [
    {
      id: "ov-agent-workflow",
      title: "受控式 Agent 工作流",
      kind: "workflow",
      body: "工程工具中的 AI 和通用 ChatBot 有本质区别——工程产出必须可靠、可审计、可追溯，任何幻觉都可能引发实车安全风险。因此设计了「受控式 Agent」范式：任务规划 → 工具调用 → 多步执行 → 人工确认。Agent 不替代工程师的决策权，而是在确定性高的环节提供效率倍增，在需要判断力的环节由人做最终确认。",
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "ov-rag-detail",
      title: "RAG 知识库全链路",
      kind: "rag",
      body: "统一知识库是所有 Agent 共享的数据基础设施：项目文档、架构模型、设计规范、历史方案 → 嵌入向量化 → 语义检索。关键设计决策：RAG 不走公开模型，全部基于私有化部署的领域数据——确保军工和航天客户的合规要求。召回率 >85%（基于 2000+ 真实工程文档的检索评测）。",
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "ov-conflict-types",
      title: "一致性校验 7 大类冲突场景",
      kind: "conflict-map",
      body: "跨文档、跨模块自动检查需求一致性——人在上百页规范中手工比对的时代结束。覆盖需求变更未同步、接口定义冲突、版本不一致、权限越界、数据模型矛盾、跨领域依赖遗漏、规范违反等七大类场景。",
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "ov-arch-detail",
      title: "Groot-Arch 三层体系架构",
      kind: "architecture",
      body: "底层：平台基础设施层（统一数据模型、权限体系、协同审批、审计日志）。中层：六个设计模块（需求/功能/系统/软件/通信/诊断）。上层：AI Agent 智能层（文档生成/模型校验/方案推荐/知识检索/一致性校验）。三层解耦，Agent 可独立迭代不影响平台稳定性。",
      sourceRefs: [{ type: "timeline" }],
    },
    {
      id: "ov-platform",
      title: "平台基础设施分层架构",
      kind: "platform",
      body: "平台层抽象了 VDE/DDE 积累的通用能力：平台管理、协同审批、数据模型、权限审计。需求、功能、系统、软件四个新模块构建在这层之上。不先做平台层，六个模块是六个孤岛，AI Agent 无法工作。先做平台层，六个模块是一个系统，AI Agent 可以在其上理解、生成、校验工程数据。",
      sourceRefs: [{ type: "timeline" }],
    },
  ],
};
