import type { ComponentType } from "react";
import type { ModuleSourceRef } from "@/lib/public-narrative/types";

export interface PresentationDraft {
  id: string;
  schemaVersion: 1;
  sourceResumeRevision: string;
  sourcePrepNarrativeId?: string;
  targetRole: string;
  template: "agent-product-arc" | "system-builder" | "growth-commercial" | "technical-project";
  slides: PresentationSlide[];
  overlays: PresentationOverlay[];
  themeId: string;
  themeTokens?: Record<string, string>;
  narrativeProfile?: InterviewNarrativeProfile;
  storyBlueprint?: InterviewStoryBlueprint;
  createdAt: string;
  updatedAt: string;
}

export interface PresentationSlide {
  id: string;
  kind: string;
  title: string;
  subtitle?: string;
  body: string;
  bullets: string[];
  visualizations?: VisualizationSpec[];
  overlayIds?: string[];
  speakerNotes?: string;
  hidden?: boolean;
  sourceRefs: ModuleSourceRef[];
  /** Pill badge next to summary line, e.g. "Phase 1 · 产品经理" */
  phaseTag?: string;
  /** Text after the phase tag pill */
  summaryLine?: string;
  /** Highlight callout boxes (gold/teal/violet themed) */
  highlightCallouts?: { title: string; body: string; variant?: "gold" | "teal" | "violet" | "blue" | "rose" | "green" | "cyan" }[];
  /** Impact cards with colored top border */
  cards?: { title: string; body: string; variant?: "gold" | "teal" | "violet" | "blue" | "rose" | "green" | "cyan" }[];
  /** Bold closing quote for resolution slide */
  closingQuote?: string;
  /** Narrative thread text for resolution slide */
  narrativeThread?: string;
  /** Feature highlight pills (for fullstack slide) */
  featurePills?: { label: string; variant?: "violet" | "blue" | "gold" }[];
  /** Domain tags (for fullstack slide) */
  domainTags?: string[];
  /** Reference-style story beats used by the controlled interview renderer/agent. */
  narrativeBeats?: string[];
  /** Higher density means more reference-style cards/diagram details. */
  layoutIntensity?: "standard" | "dense" | "reference";
  /** Structured overlay composition generated by the agent/blueprint layer. */
  overlayComposition?: OverlaySpec[];
}

export interface PresentationOverlay {
  id: string;
  title: string;
  body: string;
  kind: string;
  spec?: OverlaySpec;
  sourceRefs: ModuleSourceRef[];
}

export interface VisualizationSpec {
  type: DiagramSpec["type"];
  data: Record<string, unknown>;
}

export interface InterviewNarrativeProfile {
  presetId: string;
  confidence: number;
  candidateName: string;
  targetRole: string;
  positioning: string;
  domainContext: string[];
  evidenceKeywords: string[];
  metrics: string[];
  classifiedMetrics?: {
    teamSize?: string;
    users?: string;
    customersProjects?: string;
    efficiency?: string;
    agents?: string;
  };
  transferableCapabilities: string[];
  riskNotes: string[];
}

export interface InterviewStoryBlueprint {
  version: 1;
  presetId: string;
  title: string;
  slideArc: Array<{
    id: string;
    beat: string;
    objective: string;
    visualizationType?: DiagramSpec["type"];
    overlayIds?: string[];
  }>;
  themeTokens: Record<string, string>;
  diagrams: Record<string, DiagramSpec>;
  overlays: OverlaySpec[];
}

export interface DomainPreset {
  id: string;
  label: string;
  matchKeywords: string[];
  minKeywordHits: number;
  buildBlueprint: (profile: InterviewNarrativeProfile) => InterviewStoryBlueprint;
}

export type DiagramSpec =
  | { type: "hero-architecture"; data: Record<string, unknown> }
  | { type: "v-model"; data: Record<string, unknown> }
  | { type: "pipeline"; data: Record<string, unknown> }
  | { type: "platform-quadrants"; data: Record<string, unknown> }
  | { type: "agent-workflow"; data: Record<string, unknown> }
  | { type: "rag-flow"; data: Record<string, unknown> }
  | { type: "impact-metrics"; data: Record<string, unknown> }
  | { type: "orbit"; data: Record<string, unknown> }
  | { type: "custom"; data: Record<string, unknown> };

export interface OverlaySpec {
  id: string;
  kind: string;
  title: string;
  sections?: Array<{ title: string; body: string; tone?: "gold" | "teal" | "violet" | "blue" | "rose" | "green" | "cyan" }>;
  diagram?: DiagramSpec;
}

export type SlideRenderer = ComponentType<{
  slide: PresentationSlide;
  overlays: PresentationOverlay[];
  onOpenOverlay: (id: string) => void;
  theme: PresentationTheme;
}>;

export interface PresentationTheme {
  id: string;
  name: string;
  colors: {
    bg: string;
    bg2: string;
    surface: string;
    text: string;
    text2: string;
    text3: string;
    gold: string;
    goldDim: string;
    teal: string;
    tealDim: string;
    violet: string;
    violetDim: string;
    blue: string;
    blueDim: string;
    amber: string;
    amberDim: string;
    rose: string;
    green: string;
    cyan: string;
    border: string;
    borderStrong: string;
  };
  radius: { sm: string; lg: string };
}
